-- Word lists for Pictionary Party.
-- Each category has e=easy, m=medium, h=hard word arrays.
return {
    fr = {
        { id = "animaux", name = "Animaux", words = {
            e = { "Chat","Chien","Cheval","Lion","Lapin","Vache","Canard","Grenouille","Poisson","Oiseau","Cochon","Mouton","Chèvre","Souris","Âne","Poule","Coq","Dindon","Abeille","Papillon","Escargot","Araignée","Fourmi","Tortue","Serpent","Ours","Loup","Renard","Écureuil","Hibou","Chauve-souris","Hamster","Cerf","Sanglier","Taupe","Hérisson","Pigeon","Corbeau","Requin","Baleine" },
            m = { "Girafe","Crocodile","Pingouin","Dauphin","Kangourou","Pieuvre","Flamant","Bison","Buffle","Chameau","Lama","Panda","Koala","Gorille","Chimpanzé","Zèbre","Hippopotame","Rhinocéros","Éléphant","Autruche","Paon","Perroquet","Toucan","Méduse","Homard","Crabe","Otarie","Phoque","Loutre","Blaireau","Belette","Furet","Vison","Lynx","Puma","Jaguar","Hyène","Chacal","Antilope","Gazelle" },
            h = { "Ornithorynque","Axolotl","Pangolin","Nautile","Tapir","Tatou","Okapi","Lémur","Varan","Narval","Wombat","Capybara","Fennec","Ocelot","Manchot","Aigle royal","Vautour","Ibis","Colibri","Salamandre","Iguane","Caméléon","Scorpion","Mille-pattes","Ver de terre","Étoile de mer","Oursin","Anguille","Espadon","Raie manta","Buse","Faucon","Martre","Genette","Marmotte","Musaraigne","Loir","Tamanoir","Kinkajou","Quokka" },
        }},
        { id = "metiers", name = "Métiers", words = {
            e = { "Médecin","Pompier","Policier","Boulanger","Dentiste","Infirmier","Pilote","Facteur","Cuisinier","Professeur","Coiffeur","Serveur","Vendeur","Caissier","Chauffeur","Jardinier","Menuisier","Électricien","Plombier","Peintre","Boucher","Fleuriste","Agriculteur","Berger","Pêcheur","Marin","Soldat","Avocat","Juge","Secrétaire","Comédien","Chanteur","Danseur","Écrivain","Journaliste","Photographe","Coursier","Bibliothécaire","Guide","Traducteur" },
            m = { "Architecte","Menuisier ébéniste","Chirurgien","Rédacteur","Cameraman","Comptable","Géologue","Diplomate","Vétérinaire","Pharmacien","Ingénieur","Notaire","Assureur","Banquier","Trader","Designer","Illustrateur","Scénariste","Réalisateur","Producteur","Chercheur","Biologiste","Chimiste","Physicien","Statisticien","Urbaniste","Historien","Archéologue","Anthropologue","Sociologue","Psychologue","Psychiatre","Kinésithérapeute","Ostéopathe","Orthophoniste","Ergothérapeute","Sage-femme","Ambulancier","Douanier","Greffier" },
            h = { "Astrophysicien","Entomologiste","Paléontologue","Cartographe","Cryptologue","Épidémiologiste","Commissaire","Sophrologue","Marionnettiste","Luthier","Sommelier","Taxidermiste","Horloger","Chapelier","Tanneur","Vitrailliste","Ébéniste","Forgeron","Tonnelier","Verrier","Cordonnier","Selier","Chaudronnier","Étameur","Vannier","Feutrier","Tisserand","Restaurateur d'art","Numismate","Vulcanologue","Sismologue","Météorologue","Océanographe","Ornithologue","Herpétologue","Malacologue","Papyrologue","Héraldiste","Campanologue","Sinologue" },
        }},
        { id = "sports", name = "Sports", words = {
            e = { "Football","Tennis","Natation","Ski","Boxe","Golf","Rugby","Judo","Vélo","Basket","Karate","Gymnastique","Athlétisme","Marathon","Pétanque","Ping-pong","Bowling","Fléchette","Patinage","Surf","Voile","Escalade","Randonnée","Yoga","Musculation","Danse sportive","Trampoline","Skateboard","Roller","Baseball","Cricket","Billard","Fer à cheval","Tir à l'arc","Lutte","Boules","Course à pied","Frisbee","Hockey sur glace","Karting" },
            m = { "Escrime","Aviron","Badminton","Équitation","Plongée","Handball","Biathlon","Curling","Volley","Triathlon","Water-polo","Taekwondo","Aikido","Capoeira","Cross-fit","Snowboard","Ski nautique","Voltige","Trial","Motocross","Bobsleigh junior","Rink-hockey","Cyclocross","Duathlon","Decathlon","Heptathlon","Marche nordique","Canoë-kayak","Rafting","Parapente","Deltaplane","Base-jump","Plongeon","Natation synchronisée","Gymnastique rythmique","Tir sportif","Escrime artistique","Rink hockey","Unihockey","Netball" },
            h = { "Bobsleigh","Pentathlon","Pelote basque","Kitesurf","Luge","Crosse","Squash","Skeleton","Sumo","Polo","Kabaddi","Sepak takraw","Hurling","Chistera","Jai alai","Skijoring","Bandy","Broomball","Canne de combat","Savate","Pankration","Sambo","Kendo","Iaido","Kyudo","Jujitsu","Krav maga","Ski de vitesse","Course d'orientation","Triple saut","Lancer de marteau","Lancer du disque","Saut à la perche","Ultra-trail","Pancrace","Fat bike","Ski-alpinisme","Traîneau à chiens","Tir à la corde","Joute nautique" },
        }},
        { id = "nourriture", name = "Nourriture", words = {
            e = { "Pizza","Gâteau","Pain","Fromage","Soupe","Glace","Salade","Crêpe","Spaghetti","Omelette","Pomme","Banane","Orange","Fraise","Raisin","Carotte","Tomate","Frites","Hamburger","Sandwich","Riz","Oeuf","Beurre","Lait","Yaourt","Confiture","Miel","Chocolat","Bonbon","Biscuit","Poulet","Jambon","Saucisse","Poisson pané","Croissant","Baguette","Tarte","Muffin","Popcorn","Cornichon" },
            m = { "Quiche","Fondue","Ratatouille","Couscous","Risotto","Paella","Meringue","Artichaut","Sushi","Lasagnes","Escargots","Foie gras","Choucroute","Tartare","Ceviche","Gaspacho","Falafel","Houmous","Tempura","Dim sum","Curry","Naan","Tacos","Guacamole","Empanada","Gnocchi","Ravioli","Pesto","Tiramisu","Panna cotta","Crème brûlée","Baba au rhum","Financier","Macaron","Nougat","Calisson","Kouign-amann","Cannelé","Far breton","Galette des rois" },
            h = { "Bourguignon","Millefeuille","Bouillabaisse","Cassoulet","Profiteroles","Blanquette","Gougères","Croquembouche","Tatin","Vichyssoise","Consommé","Velouté","Tartiflette","Aligot","Pot-au-feu","Andouillette","Boudin noir","Rillettes","Confit de canard","Tapenade","Baklava","Pavlova","Souffle","Vacherin","Charlotte","Kougelhopf","Brioche perdue","Clafoutis","Feuilleté","Pâté en croûte","Terrine","Quenelle","Bouchée à la reine","Poule au pot","Navarin","Fricassée","Estouffade","Civet","Marmelade","Compote" },
        }},
        { id = "lieux", name = "Lieux", words = {
            e = { "Plage","Montagne","Forêt","Gare","Aéroport","Marché","Église","École","Hôpital","Château","Ferme","Village","Ville","Parc","Piscine","Cinéma","Restaurant","Hôtel","Zoo","Musée","Pont","Tunnel","Route","Trottoir","Jardin","Cimetière","Mairie","Banque","Poste","Supermarché","Boulangerie","Pharmacie","Garage","Usine","Chantier","Camping","Refuge","Commissariat","Caserne de pompiers","Terrain de jeux" },
            m = { "Désert","Volcan","Phare","Mosquée","Fjord","Monastère","Stade","Bibliothèque","Grotte","Port","Cascade","Falaise","Marais","Prairie","Vallée","Colline","Plateau","Canyon","Oasis","Steppe","Toundra","Savane","Jungle","Iceberg","Glacier","Récif","Lagon","Delta","Archipel","Péninsule","Synagogue","Temple","Pagode hindoue","Cathédrale","Basilique","Chapelle","Abbaye","Forteresse","Citadelle","Douves" },
            h = { "Catacombes","Atoll","Pagode","Estuaire","Bunker","Labyrinthe","Mégalithe","Citerne","Crypte","Léproserie","Nécropole","Ziggourat","Amphithéâtre","Aqueduc","Thermes romains","Caravansérail","Kasbah","Souk","Médina","Minaret","Ossuaire","Mausolée","Cénotaphe","Observatoire","Planétarium","Herbier","Serre tropicale","Volcanière","Fumerolle","Solfatare","Doline","Gouffre","Reg","Erg","Hamada","Wadi","Playa","Salar","Fjeld","Cirque glaciaire" },
        }},
        { id = "objets", name = "Objets", words = {
            e = { "Clé","Chaise","Lampe","Téléphone","Sac","Livre","Horloge","Parapluie","Ballon","Marteau","Table","Assiette","Verre","Fourchette","Couteau","Cuillère","Casserole","Poêle","Coussin","Couverture","Miroir","Brosse","Peigne","Savon","Serviette","Valise","Ceinture","Portefeuille","Lunettes","Montre","Stylo","Crayon","Gomme","Règle","Ciseaux","Colle","Agrafeuse","Enveloppe","Timbre","Carte postale" },
            m = { "Microscope","Télescope","Accordéon","Sablier","Compas","Arrosoir","Balançoire","Ventilateur","Trampoline","Harmonica","Boussole","Jumelles","Loupe","Bougeoir","Lanterne","Réveil","Balance","Thermomètre","Baromètre","Manomètre","Chevalet","Palette","Pinceau","Ciseau à bois","Rabot","Enclume","Étau","Perceuse","Scie","Lime","Métier à tisser","Fuseau","Rouet","Dévidoir","Cadran solaire","Girouette","Moulin à vent","Puits","Charrue","Faucille" },
            h = { "Sextant","Alambic","Trépied","Tire-bouchon","Soufflet","Pluviomètre","Équerre","Décapsuleur","Astrolabe","Métronome","Théodolite","Sismographe","Pendule de Foucault","Cadran lunaire","Clepsydre","Kaleidoscope","Stéréoscope","Zootrope","Praxinoscope","Gramophone","Télégraphe","Sextuor optique","Rouet à pédale","Dévidoir à bobines","Chausse-pied","Tisonnier","Soufflet de forge","Marteau-piqueur","Niveau à bulle","Fil à plomb","Compas de marine","Octant","Gnomon","Anémomètre","Hygromètre","Altimètre","Sonar portatif","Radiomètre","Spectroscope","Polarimètre" },
        }},
        { id = "nature", name = "Nature", words = {
            e = { "Soleil","Nuage","Arbre","Rivière","Fleur","Pluie","Arc-en-ciel","Rocher","Étoile","Vague","Lune","Ciel","Herbe","Feuille","Branche","Racine","Graine","Champignon","Mousse","Sable","Colline","Forêt","Lac","Île","Neige","Glace","Vent","Orage","Éclair","Bruine","Rosée","Brouillard","Ruisseau","Marais","Prairie","Buisson","Fougère","Lierre","Cactus","Bambou" },
            m = { "Tornade","Aurore boréale","Stalactite","Glacier","Foudre","Marécage","Dune","Volcan","Geyser","Tourbillon","Stalagmite","Falaise","Canyon","Delta","Estuaire","Récif corallien","Toundra","Savane","Mangrove","Tourbière","Méandre","Cascade","Grotte","Iceberg fondu","Banquise","Avalanche","Ouragan","Cyclone","Typhon","Mousson","Arc lunaire","Halo solaire","Mirage","Bioluminescence","Photosynthèse","Pollinisation","Symbiose","Écosystème","Biotope","Permafrost" },
            h = { "Éclipse","Moraine","Embrun","Crevasse","Confluent","Épiphyte","Karst","Limon","Atoll","Serac","Fumerolle","Solfatare","Doline","Lapiaz","Drumlin","Esker","Loess","Playa","Salar","Fjeld","Nébuleuse","Aérosol naturel","Thermokarst","Paléosol","Varve","Tillite","Régolithe","Sapropel","Travertin","Geode","Fulgurite","Tectite","Pergélisol","Solifluxion","Cryoturbation","Nivation","Déflation éolienne","Corrasion","Bioturbation","Halocline" },
        }},
        { id = "activites", name = "Activités", words = {
            e = { "Courir","Nager","Chanter","Danser","Peindre","Cuisiner","Lire","Jardiner","Grimper","Sauter","Dessiner","Écrire","Marcher","Sourire","Dormir","Manger","Boire","Voler (avion)","Conduire","Pêcher","Chasser","Nettoyer","Balayer","Laver","Plier","Coudre","Repasser","Construire","Réparer","Peindre un mur","Planter","Arroser","Récolter","Cueillir","Empiler","Porter","Pousser","Tirer","Lancer","Attraper" },
            m = { "Tricoter","Escalader","Surfer","Méditer","Sculpter","Jongler","Plonger","Camper","Tracter","Souffler","Patiner","Skier","Ramer","Pagayer","Grimper à la corde","Faire du vélo","Faire du cheval","Faire du tir à l'arc","Faire de la voile","Faire du kayak","Faire du yoga","Faire de la boxe","Faire de l'escrime","Faire de la poterie","Tisser","Broder","Filer la laine","Forger","Souffler du verre","Tailler la pierre","Négocier","Débattre","Enseigner","Diriger un orchestre","Composer","Improviser","Chorégraphier","Mettre en scène","Réaliser un film","Monter un spectacle" },
            h = { "Distiller","Sertir une pierre","Cartographier","Fermenter","Labourer","Émailler","Calligraphier","Spéléologuer","Équilibrer","Scarifier","Tanner le cuir","Ciseler","Marqueter","Restaurer un tableau","Étalonner un instrument","Herboriser","Naturaliser un animal","Vitrailler","Ferrer un cheval","Vanner le grain","Distiller un alcool","Affiner un fromage","Vendanger","Fouler le raisin","Écimer la vigne","Greffer un arbre","Tailler un bonsai","Faire de la fauconnerie","Dresser un rapace","Faire du funambulisme","Faire du unicycle","Jongler avec des torches","Faire de la ventriloquie","Faire de l'origami","Faire de la marqueterie","Faire de la dorure","Restaurer un livre ancien","Relier un livre","Faire de la sertisserie","Faire de la damasquinure" },
        }},
        { id = "transports", name = "Transports", words = {
            e = { "Voiture","Vélo","Bus","Train","Avion","Bateau","Moto","Camion","Taxi","Tramway","Métro","Scooter","Trottinette","Skateboard","Roller","Charrette","Calèche","Traîneau","Ballon dirigeable","Fourgonnette","Voiture de police","Ambulance","Camion de pompiers","Pédalo","Canoë","Kayak","Voilier","Ferry","Téléphérique","Funiculaire","Corbillard","Fourgon","Camping-car","Remorque","Diligence","Pousse-pousse","Tuk-tuk","Vespa","Quad","Trottinette électrique" },
            m = { "Hélicoptère","Sous-marin","Paquebot","Voilier trois-mats","Zeppelin","Deltaplane","Parapente","Montgolfière","Traîneau à chiens","Draisine","Locomotive à vapeur","Tramway historique","Télécabine","Téléski","Hovercraft","Hydravion","Planeur","Ulm","Motoneige","Jet ski","Camion-benne","Grue mobile","Bulldozer","Tractopelle","Chariot élévateur","Semi-remorque","Wagon-citerne","Péniche","Chaland","Vedette","Trimaran","Catamaran","Kitesurf tracté","Char à voile","Véhicule amphibie","Autocar","Minibus","Berline","Break","Cabriolet" },
            h = { "Aéroglisseur","Dirigeable rigide","Sous-marin nucléaire","Brise-glace","Cargo porte-conteneurs","Pétrolier","Navire-usine","Bathyscaphe","Navette spatiale","Fusée","Module lunaire","Rover martien","Zeppelin militaire","Autogire","Aile volante","Avion cargo","Avion-citerne","Chasse-neige","Draisine motorisée","Wagon-lit","Wagon-restaurant","Train à grande vitesse","Monorail","Funiculaire à crémaillère","Téléférique alpin","Traîneau à voile","Bobsleigh de transport","Char à boeufs","Palanquin","Brouette motorisée","Véhicule chenillé","Half-track","Amphibie militaire","Hydroptère","Trimaran de course","Voilier polaire","Baleinière","Sous-marin de poche","Véhicule lunaire","Capsule spatiale" },
        }},
        { id = "corps", name = "Corps humain", words = {
            e = { "Tête","Main","Pied","Oeil","Nez","Bouche","Oreille","Bras","Jambe","Doigt","Genou","Coude","Épaule","Dos","Ventre","Cou","Menton","Sourcil","Cil","Dent","Cheveux","Ongle","Cheville","Poignet","Talon","Nombril","Joue","Front","Lèvre","Langue","Peau","Muscle","Os","Coeur","Poumon","Cerveau","Squelette","Sang","Veine","Pouce" },
            m = { "Foie","Estomac","Rein","Intestin","Vessie","Colonne vertébrale","Côte","Clavicule","Tendon","Ligament","Pupille","Rétine","Iris","Tympan","Larynx","Pharynx","Trachée","Bronches","Diaphragme","Rate","Pancréas","Vésicule biliaire","Aorte","Artère","Nerf","Cartilage","Moelle épinière","Glande thyroïde","Hypophyse","Follicule pileux","Empreinte digitale","Cuticule","Aisselle","Nuque","Tempe","Pommette","Fossette","Cicatrice","Grain de beauté","Ride" },
            h = { "Uretère","Sphincter","Péritoine","Endocarde","Myocarde","Synapse","Neurone","Hémoglobine","Lymphe","Ganglion lymphatique","Thymus","Cortex cérébral","Cervelet","Hypothalamus","Bulbe rachidien","Uvule","Amygdale","Épiglotte","Méninge","Sclérotique","Cornée","Cristallin","Choroïde","Osselet de l'oreille","Cochlée","Placenta","Fontanelle","Omoplate","Sternum","Humérus","Fémur","Rotule","Tibia","Péroné","Radius","Cubitus","Vertèbre","Bassin","Trachée-artère","Appendice" },
        }},
        { id = "vetements", name = "Vêtements", words = {
            e = { "Chemise","Pantalon","Robe","Jupe","Chaussure","Chaussette","Chapeau","Manteau","Veste","Pull","Short","Maillot de bain","Gant","Écharpe","Bonnet","Ceinture","Cravate","Botte","Sandale","Pyjama","Tablier","Casquette","Legging","Collant","Jean","T-shirt","Gilet","Imperméable","Sous-vêtement","Debardeur","Foulard","Chausson","Bavoir","Salopette","Robe de chambre","Bottes de pluie","Moufle","Bretelle","Noeud papillon","Voile de mariée" },
            m = { "Kimono","Sari","Kilt","Poncho","Sombrero","Turban","Costume trois-pièces","Smoking","Toge","Cape","Cagoule","Combinaison de ski","Combinaison de plongée","Gilet pare-balles","Armure","Chasuble","Soutane","Uniforme militaire","Blouse de laboratoire","Tenue de chirurgien","Kimono de judo","Tenue de flamenco","Sarong","Boubou","Djellaba","Hijab","Chapeau melon","Haut-de-forme","Corset","Crinoline","Guêtres","Cape de pluie","Salopette de travail","Combinaison spatiale","Justaucorps","Tutu","Maillot de danseur","Costume de scène","Peignoir","Kilt écossais" },
            h = { "Chausson de pointe","Guimpe","Fraise (col)","Vertugadin","Panier (jupon)","Redingote","Frac","Jaquette","Gibus","Bicorne","Tricorne","Casque à pointe","Heaume","Cotte de mailles","Gantelet","Cuissard d'armure","Braies","Peplum","Toge romaine","Chlamyde","Sabots","Galoches","Espadrilles anciennes","Chapeau claqué","Faux-col","Plastron","Guêtres de cuir","Manteau de fourrure","Étole","Manchon","Ombrelle","Face-à-main","Monocle","Lorgnon","Bandeau de geisha","Obi","Yukata","Hakama","Zori","Geta" },
        }},
        { id = "musique", name = "Musique", words = {
            e = { "Guitare","Piano","Violon","Batterie","Flûte","Trompette","Tambour","Micro","Casque audio","Radio","Chanteur","Musicien","Concert","Note de musique","Partition","Cloche","Tambourin","Maracas","Triangle (instrument)","Xylophone","Harpe","Clarinette","Saxophone","Trombone","Orgue","Accordéon","Ukulélé","Banjo","Cymbale","Métronome","Chorale","Karaoke","Disque vinyle","Enceinte","Baguette de chef d'orchestre","Pupitre","Boîte à musique","Sifflet","Grelot","Clavier" },
            m = { "Violoncelle","Contrebasse","Hautbois","Basson","Cor d'harmonie","Tuba","Cornemuse","Didgeridoo","Sitar","Kora","Balalaika","Mandoline","Luth","Vielle à roue","Cymbalum","Marimba","Vibraphone","Celesta","Clavecin","Orgue de barbarie","Theremin","Synthétiseur","Boîte à rythmes","Table de mixage","Diapason","Chef d'orchestre","Compositeur","Librettiste","Choriste","Soliste","Symphonie","Concerto","Opéra","Opérette","Fanfare","Big band","Quatuor à cordes","Trio jazz","Chorale gospel","Orchestre philharmonique" },
            h = { "Théorbe","Vielle médiévale","Serpent (instrument)","Ophicleide","Sacqueboute","Cromorne","Cornemuse écossaise","Duduk","Erhu","Shamisen","Koto","Guzheng","Pipa","Santur","Oud","Bouzouki","Charango","Cuatro vénézuélien","Berimbau","Steel drum","Hang drum","Glass harmonica","Ondes Martenot","Basse continue","Contrepoint","Fugue","Solfège","Neume","Tablature","Diapason étalon","Luthier au travail","Clavicorde","Épinette","Virginal","Regale","Vielle organistrum","Cistre","Archiluth","Mandore","Rebec" },
        }},
        { id = "technologie", name = "Technologie", words = {
            e = { "Ordinateur","Téléphone portable","Télévision","Tablette","Souris (ordinateur)","Clavier","Écran","Imprimante","Appareil photo","Casque VR","Console de jeux","Manette","Clé USB","Chargeur","Écouteurs","Enceinte connectée","Robot","Drone","Caméra","Webcam","Routeur wifi","Batterie","Ampoule LED","Interrupteur","Prise électrique","Câble","Antenne","Satellite","Puce électronique","Carte SIM","Montre connectée","Liseuse","Scanner","Photocopieuse","Fax","Talkie-walkie","Télécommande","Minuteur","Détecteur de fumée","Aspirateur robot" },
            m = { "Processeur","Carte mère","Disque dur","Serveur","Réseau neuronal","Circuit imprimé","Transistor","Diode","Condensateur","Résistance électrique","Imprimante 3D","Scanner 3D","Bras robotise","Capteur de mouvement","Écran tactile","Réalité augmentée","Casque de réalité virtuelle","Intelligence artificielle","Algorithme","Base de données","Fibre optique","Modem","Onduleur","Panneau solaire","Éolienne","Pile à combustible","Batterie lithium","Puce RFID","Code-barres","Lecteur biométrique","Exosquelette","Bionique","Nanorobot","Imprimante braille","Synthétiseur vocal","Traducteur automatique","Assistant vocal","Casque à réduction de bruit","Manette haptique","Simulateur de vol" },
            h = { "Semi-conducteur","Supraconducteur","Qubit","Ordinateur quantique","Réseau de neurones profond","Machine de Turing","Automate cellulaire","Circuit intégré","Micro-onduleur","Accélérateur de particules","Cyclotron","Synchrotron","Spectromètre de masse","Interféromètre","Gyroscope laser","Capteur infrarouge","Détecteur de particules","Réacteur à fusion","Réacteur à fission","Centrifugeuse","Cage de Faraday","Bobine de Tesla","Générateur Van de Graaff","Oscilloscope","Analyseur de spectre","Amplificateur opérationnel","Convertisseur analogique-numérique","Photodiode","Laser à excimère","Guide d'ondes","Métamatériau","Cristal photonique","Biopuce","Neuroprothèse","Interface cerveau-machine","Nanotube de carbone","Graphène","Impression bio 3D","Robot chirurgical","Satellite d'observation" },
        }},
        { id = "espace", name = "Espace", words = {
            e = { "Fusée","Astronaute","Planète","Lune","Étoile","Soleil","Terre","Comète","Satellite","Navette spatiale","Casque d'astronaute","Combinaison spatiale","Station spatiale","Météorite","Trou noir","Galaxie","Voie lactée","Constellation","Télescope","Observatoire","Mars","Jupiter","Saturne","Venus","Mercure (planète)","Uranus","Neptune","Pluton","Astéroïde","Nébuleuse","Orbite","Cratère lunaire","Anneau de Saturne","Extraterrestre","Soucoupe volante","Base lunaire","Rover spatial","Antenne parabolique","Fusée à étages","Capsule de retour" },
            m = { "Trou de ver","Supernova","Naine blanche","Étoile à neutrons","Système solaire","Ceinture d'astéroïdes","Ceinture de Kuiper","Nuage d'Oort","Exoplanète","Zone habitable","Gravité","Apesanteur","Rayon cosmique","Vent solaire","Aurore polaire","Éclipse solaire","Éclipse lunaire","Marées terrestres","Rotation terrestre","Révolution planétaire","Sonde spatiale","Module d'atterrissage","Bras robotique spatial","Panneau solaire spatial","Combinaison pressurisée","Scaphandre spatial","Fusée réutilisable","Lanceur lourd","Tour de lancement","Pas de tir","Radiotélescope","Télescope spatial","Interféromètre spatial","Spectrographe stellaire","Horloge atomique spatiale","Boussole stellaire","Carte du ciel","Planétarium numérique","Simulateur de vol spatial","Centre de contrôle" },
            h = { "Quasar","Pulsar","Magnétar","Trou noir supermassif","Matière noire","Énergie sombre","Rayonnement fossile","Big Bang","Singularité gravitationnelle","Horizon des événements","Lentille gravitationnelle","Naine brune","Géante rouge","Hypergéante bleue","Amas globulaire","Amas de galaxies","Filament cosmique","Vide cosmique","Disque d'accrétion","Jet relativiste","Onde gravitationnelle","Boson de Higgs","Antimatière","Photon gamma","Rayon X cosmique","Sonde interstellaire","Voile solaire","Propulsion ionique","Propulsion nucléaire thermique","Cryogénisation spatiale","Terraformation","Habitat spatial rotatif","Ascenseur spatial","Point de Lagrange","Manoeuvre d'assistance gravitationnelle","Fenêtre de lancement","Orbite géostationnaire","Orbite polaire","Rentrée atmosphérique","Bouclier thermique" },
        }},
        { id = "fantastique", name = "Fantastique", words = {
            e = { "Dragon","Sorcière","Fantôme","Vampire","Fée","Licorne","Château hanté","Baguette magique","Sorcier","Monstre","Loup-garou","Zombie","Squelette","Momie","Géant","Nain","Elfe","Troll","Gobelin","Ogre","Chaudron","Balai volant","Boule de cristal","Potion magique","Tapis volant","Génie de la lampe","Épée magique","Bouclier","Bague magique","Grimoire","Cape d'invisibilité","Chapeau pointu","Cristal magique","Amulette","Sortilège","Malédiction","Familier (animal)","Portail magique","Coffre au trésor","Carte au trésor" },
            m = { "Sirène","Centaure","Griffon","Phénix","Hydre","Cyclope","Minotaure","Sphinx","Pégase","Chimère","Kraken","Basilic","Golem","Nécromancien","Chevalier noir","Barde","Druide","Paladin","Ranger elfe","Archimage","Portail dimensionnel","Cristal de mana","Parchemin enchanté","Épée runique","Armure enchantée","Anneau de pouvoir","Orbe magique","Talisman","Runes anciennes","Cercle d'invocation","Forteresse des ténèbres","Tour de mage","Village elfe","Forêt enchantée","Marais maudit","Volcan des ombres","Portail des enfers","Cité perdue","Temple oublié","Ruines antiques" },
            h = { "Lich","Demi-dieu","Titan","Chimère ailée","Wyverne","Hippogriffe","Kelpie","Banshee","Selkie","Djinn","Rakshasa","Yokai","Oni","Kappa","Tanuki magique","Baku (mangeur de rêves)","Naga","Garuda","Manticore","Cockatrice","Homoncule","Gargouille vivante","Esprit élémentaire","Élémentaire de feu","Élémentaire d'eau","Élémentaire de terre","Élémentaire d'air","Avatar divin","Reliques sacrées","Pierre philosophale","Portail interdimensionnel","Sceau magique ancien","Malédiction ancestrale","Prophétie","Oracle mystique","Gardien spectral","Âme errante","Esprit frappeur","Chasseur de primes fantastique","Alchimiste légendaire" },
        }},
        { id = "cinema", name = "Cinéma et TV", words = {
            e = { "Caméra","Écran de cinéma","Popcorn","Ticket de cinéma","Fauteuil de cinéma","Projecteur","Réalisateur","Acteur","Actrice","Scénario","Clap de cinéma","Micro-perche","Costume de cinéma","Maquillage","Plateau de tournage","Storyboard","Bande-annonce","Générique","Télécommande TV","Antenne TV","Écran plat","Console de jeux (salon)","DVD","Manette de jeu","Dessin animé","Super-héros","Super-vilain","Cascade","Effets spéciaux","Bobine de film","Salle obscure","Fauteuil inclinable","Distributeur de bonbons","Affiche de film","Étoile sur trottoir (Hollywood)","Caméra de surveillance","Drone de tournage","Grue de cinéma","Fond vert","Perche à micro" },
            m = { "Chef opérateur","Monteur","Ingénieur du son","Doubleur","Cascadeur","Marionnettiste de cinéma","Décorateur","Costumier","Maquilleur spécial","Producteur exécutif","Scénariste","Compositeur de musique de film","Étalonneur","Perchman","Régisseur","Script-doctor","Casting","Avant-première","Festival de cinéma","Tapis rouge","Prix cinématographique","Nomination aux Oscars","Effets visuels numériques","Animation image par image","Motion capture","Fond bleu","Travelling (camera)","Steadicam","Grue-caméra","Drone cinéma","Série télévision","Saison (TV)","Épisode pilote","Spin-off","Reboot","Documentaire","Court-métrage","Long-métrage","Film muet","Film en noir et blanc" },
            h = { "Anamorphose optique","Kinétoscope","Zootrope","Praxinoscope","Camera obscura","Pellicule argentique","Développement de film","Monteur négatif","Étalonnage numérique","Chef décorateur","Ensemblier","Accessoiriste","Régisseur général","Directeur de casting","Coach dialogue","Chef cascadeur","Coordinateur de cascades","Technicien effets pratiques","Animatronique","Marionnette animatronique","Matte painting","Rotoscopie","Chroma key avancé","Capture de performance","Scan facial 3D","Rendu numérique","Colorimétrie","Mixage son 5.1","Foley (bruitage)","Bruiteur","Synchronisation labiale","Sous-titrage","Doublage voix","Distribution internationale","Classification cinématographique","Cinémathèque","Restauration de film ancien","Archive filmique","Projection 70mm","Cinéma en plein air" },
        }},
        { id = "fetes", name = "Fêtes et célébrations", words = {
            e = { "Sapin de Noël","Cadeau","Père Noël","Bougie d'anniversaire","Gâteau d'anniversaire","Ballon de fête","Confetti","Feu d'artifice","Guirlande","Citrouille d'Halloween","Costume d'Halloween","Bonbon","Oeuf de Pâques","Lapin de Pâques","Fleur de mariage","Bague de fiançailles","Pièce montée","Faire-part","Bougie","Champagne","Serpentin","Chapeau de fête","Masque de carnaval","Cotillon","Pétard","Étoile filante (déco)","Calendrier de l'avent","Couronne de Noël","Botte de Noël","Traîneau du Père Noël","Renne","Bonhomme de neige","Boule de Noël","Cloche de Noël","Bas de Noël","Dinde de Noël","Bûche de Noël","Chandelier","Lanterne de fête","Drapeau de fête" },
            m = { "Feux de la Saint-Jean","Char de carnaval","Défilé de carnaval","Confettis de mariage","Voile de mariée","Alliance","Demoiselle d'honneur","Témoin de mariage","Pièce de gâteau","Baptême","Communion","Bar mitzvah","Diplôme de remise","Toge de remise de diplôme","Toque de graduation","Retraite aux flambeaux","Bal masqué","Réveillon","Compte à rebours nouvel an","Cotillons du nouvel an","Lanterne chinoise","Dragon du nouvel an chinois","Feux d'artifice du 14 juillet","Drapeau tricolore","Guirlande lumineuse","Vitrine de Noël","Marché de Noël","Chocolat de Pâques","Chasse aux oeufs","Panier de Pâques","Déguisement de sorcière","Bonbon ou sort","Sculpture sur citrouille","Toile d'araignée décorative","Squelette décoratif","Cimetière décoratif d'Halloween","Fanfare de défilé","Char fleuri","Confettis en papier","Cracker de Noël" },
            h = { "Piñata","Guirlande de Diwali","Lampe à huile de Diwali","Rangoli","Lanterne de Hanouka","Chandelier à neuf branches","Toupie de Hanouka","Galette de fête du printemps","Danse du lion","Danse du dragon","Pétard chinois traditionnel","Enveloppe rouge (étrennes)","Costume de mardi gras","Masque vénitien","Char de Rio","Samba de carnaval","Confettis de Rio","Fête des lanternes","Lanterne flottante","Bateau-lanterne","Fête de la mi-automne","Gâteau de lune","Fête du muguet","Brin de muguet","Fête des rois (galette)","Fève de la galette","Couronne de l'avent","Chandelle de l'avent","Marmiton de Noël","Santon de crèche","Crèche de Noël","Étoile de Bethléem (déco)","Guirlande de houx","Bouquet de gui","Costume de Sinterklaas","Sabot pour cadeaux","Bonhomme en pain d'épices","Village en pain d'épices","Sucre d'orge","Grelot de traîneau" },
        }},
        { id = "ecole", name = "École", words = {
            e = { "Cartable","Cahier","Stylo","Crayon","Gomme","Règle","Tableau noir","Craie","Bureau d'écolier","Trousse","Livre scolaire","Classe","Récréation","Cour d'école","Cantine","Bus scolaire","Uniforme scolaire","Bulletin scolaire","Devoir","Examen","Copie d'examen","Note (évaluation)","Diplôme","Calculatrice","Compas (géométrie)","Équerre","Taille-crayon","Feutre","Surligneur","Classeur","Agenda scolaire","Casier scolaire","Cloche d'école","Récré (jeu de cour)","Craie de couleur","Ardoise","Globe terrestre","Carte du monde (classe)","Squelette (cours SVT)","Microscope scolaire" },
            m = { "Amphithéâtre","Laboratoire de sciences","Salle informatique","Gymnase scolaire","Bibliothèque scolaire","Infirmerie scolaire","Proviseur","Conseiller d'éducation","Surveillant","Professeur principal","Emploi du temps","Conseil de classe","Redoublement","Orientation scolaire","Stage professionnel","Sortie scolaire","Voyage scolaire","Échange linguistique","Cours de soutien","Devoirs à la maison","Rentrée scolaire","Vacances scolaires","Baccalauréat","Brevet des collèges","Concours d'entrée","Dissertation","Exposé oral","Présentation PowerPoint","Projet de groupe","Club scolaire","Orchestre scolaire","Équipe sportive scolaire","Journal scolaire","Radio scolaire","Foyer des élèves","Internat","Pensionnat","Cantine scolaire (plateau repas)","Distributeur scolaire","Photocopieuse d'école" },
            h = { "Amphithéâtre universitaire","Salle de thèse","Jury de soutenance","Mémoire de master","Thèse de doctorat","Directeur de thèse","Laboratoire de recherche universitaire","Bourse d'études","Échange Erasmus","Colloque académique","Publication scientifique","Comité de lecture","Plagiat académique","Antisèche","Bizutage (rite étudiant)","Association étudiante","Amicale des anciens élèves","Cursus honorum scolaire","Classe préparatoire","Grande école","École normale supérieure","Agrégation (concours)","Habilitation à diriger des recherches","Postdoctorat","Sabbatique universitaire","Chaire universitaire","Doyen de faculté","Recteur d'académie","Inspecteur d'académie","Pédagogie Montessori","Pédagogie Freinet","Enseignement à distance","Classe inversée","Tableau blanc interactif","Massive open online course","Certification professionnelle","Validation des acquis","Formation continue","Apprentissage en alternance","École doctorale" },
        }},
        { id = "maison", name = "Maison", words = {
            e = { "Table","Chaise","Lit","Canapé","Armoire","Étagère","Frigo","Four","Évier","Douche","Baignoire","Toilettes","Porte","Fenêtre","Escalier","Tapis","Rideau","Coussin","Oreiller","Couette","Lampe de bureau","Télévision (salon)","Télécommande","Placard","Commode","Tiroir","Cintre","Balai","Aspirateur","Serpillière","Poubelle","Boîte aux lettres","Sonnette","Clé de maison","Toit","Cheminée","Garage","Jardin (maison)","Clôture","Portail" },
            m = { "Buanderie","Machine à laver","Sèche-linge","Lave-vaisselle","Micro-ondes","Grille-pain","Bouilloire","Cafetière","Mixeur","Robot ménager","Chauffe-eau","Chaudière","Radiateur","Climatiseur","Ventilateur de plafond","Store","Volet roulant","Verrière","Mezzanine","Grenier","Cave","Sous-sol","Terrasse","Véranda","Pergola","Balcon","Portique de jardin","Tondeuse à gazon","Brouette","Rateau","Arrosoir de jardin","Serre de jardin","Composteur","Barbecue","Piscine (jardin)","Jacuzzi extérieur","Abri de jardin","Cabane de jardin","Puits (maison)","Fontaine de jardin" },
            h = { "Vide-ordures","Monte-charge domestique","Ascenseur privé","Chambre froide domestique","Cave à vin","Cellier","Buanderie professionnelle","Local technique","Système domotique","Thermostat connecté","Détecteur de monoxyde de carbone","Volet anti-effraction","Coffre-fort mural","Alarme domestique","Interphone vidéo","Serrure connectée","Store bioclimatique","Puits de lumière","Verrière d'atelier","Charpente apparente","Poutre maîtresse","Solive","Chevron (charpente)","Faitage de toit","Gouttière","Descente d'eau pluviale","Regard d'égout","Fosse septique","Puisard","Citerne d'eau de pluie","Panneau solaire thermique","Pompe à chaleur","Récupérateur de chaleur","VMC double flux","Isolation phonique","Isolation thermique","Pare-vapeur","Bardage extérieur","Enduit de façade","Corniche architecturale" },
        }},
        { id = "jouets", name = "Jouets", words = {
            e = { "Poupée","Ours en peluche","Ballon","Cerf-volant","Toupie","Yoyo","Puzzle","Domino","Cubes","Voiture jouet","Train jouet","Robot jouet","Marionnette","Corde à sauter","Bille","Jeu de cartes","Jeu de dames","Échiquier","Trottinette jouet","Tricycle","Poussette de poupée","Maison de poupée","Ferme jouet","Coffre à jouets","Ballon de baudruche","Toboggan","Balançoire","Bac à sable","Pistolet à eau","Bulles de savon","Instrument de musique jouet","Tambour jouet","Xylophone jouet","Peluche lapin","Peluche chien","Figurine d'action","Château fort jouet","Pâte à modeler","Kaleidoscope jouet","Boîte à musique jouet" },
            m = { "Cheval à bascule","Toupie gyroscopique","Yoyo professionnel","Boîte à surprise","Casse-tête en bois","Meccano","Kaplas","Circuit de voitures","Piste de billes","Château gonflable","Cerf-volant acrobatique","Drone jouet","Robot télécommandé","Voiture radiocommandée","Bateau radiocommandé","Avion jouet","Fusée jouet","Marionnette à fils","Marionnette à gaine","Théâtre de marionnettes","Jeu de société","Jeu de rôle jouet","Figurine articulee","Diorama jouet","Maquette à assembler","Modèle réduit","Train électrique","Circuit électrique jouet","Loupe jouet","Microscope jouet","Télescope jouet","Globe jouet","Jeu de construction","Blocs de construction géants","Toupie à lancer","Cerceau (jouet)","Diabolo","Bilboquet","Jeu de fléchette","Flèche de nerf" },
            h = { "Automate mécanique","Boîte à musique ancienne","Poupée de porcelaine antique","Cheval à bascule ancien","Zootrope jouet","Praxinoscope jouet","Théâtre d'ombres","Lanterne magique","Jeu de l'oie antique","Toupie en bois tourné","Jeu de quilles anciennes","Diorama historique","Maquette de bateau ancien","Modèle réduit d'avion ancien","Train à vapeur miniature","Circuit ferroviaire miniature élaboré","Marionnette de théâtre balinais","Marionnette javanaise","Poupée russe (matriochka)","Toupie chantante","Jouet mécanique à ressort","Automate à manivelle","Kaleidoscope artisanal","Stéréoscope jouet ancien","Jouet optique rétro","Jeu de patience ancien","Casse-tête de fer","Puzzle 3D complexe","Bilboquet artisanal","Diabolo professionnel","Cerf-volant traditionnel japonais","Cerf-volant de combat indien","Toupie de compétition","Jouet articulé médiéval","Figurine de plomb ancienne","Soldat de plomb","Jouet en fer-blanc","Voiture en fer-blanc à clé","Robot en fer-blanc vintage","Manège miniature" },
        }},
        { id = "ocean", name = "Océan", words = {
            e = { "Poisson","Requin","Baleine","Dauphin","Pieuvre","Étoile de mer","Crabe","Coquillage","Vague","Plage","Bateau","Voilier","Ancre","Filet de pêche","Phare","Sable","Palmier","Bouée","Masque de plongée","Tuba (plongée)","Palmes de plongée","Serviette de plage","Parasol","Château de sable","Coquille Saint-Jacques","Homard","Crevette","Huître","Moule","Algue","Mouette","Pélican","Île déserte","Récif","Sous-marin","Perle","Corail","Méduse","Tortue de mer","Phoque" },
            m = { "Requin-marteau","Requin-baleine","Orque","Cachalot","Narval","Otarie","Morse","Lamantin","Poisson-clown","Poisson-globe","Hippocampe","Poulpe géant","Calmar","Seiche","Raie","Anguille de mer","Espadon","Thon","Barracuda","Piranha marin","Île volcanique","Atoll corallien","Lagon turquoise","Fosse océanique","Courant marin","Marée haute","Marée basse","Vague de tempête","Tsunami","Cyclone tropical","Bateau de pêche","Chalutier","Cargo","Pétrolier","Voilier de course","Catamaran","Plongée sous-marine","Bouteille de plongée","Combinaison de plongée","Détendeur" },
            h = { "Abysse","Fosse des Mariannes","Poisson-lanterne","Poisson-vipère","Calmar géant","Poulpe Dumbo","Ver à tube géant","Crabe yeti","Crevette pistolet","Corail noir","Cheminée hydrothermale","Bactérie chimiosynthétique","Concombre de mer abyssal","Anglerfish","Poisson-hache","Requin lutin","Requin-lézard","Beluga","Dugong","Otarie à fourrure","Bathyscaphe","Submersible d'exploration","Sonar à balayage latéral","Carottage sédimentaire marin","Bouée océanographique","Courant de Humboldt","Gyre océanique","Upwelling","Thermocline","Halocline","Récif frangeant","Récif barrière","Mangrove littorale","Herbier marin","Zone bathyale","Zone abyssale","Zone hadale","Plancton bioluminescent","Nautile à chambres","Argonaute" },
        }},
        { id = "meteo", name = "Météo", words = {
            e = { "Soleil","Pluie","Nuage","Neige","Vent","Orage","Éclair","Tonnerre","Arc-en-ciel","Brouillard","Grêle","Verglas","Canicule","Vague de froid","Parapluie","Imperméable","Bottes de pluie","Thermomètre","Girouette","Nuage noir","Ciel bleu","Ciel étoilé","Rosée du matin","Givre","Gelée blanche","Bourrasque de vent","Flocon de neige","Bonhomme de neige","Bataille de boules de neige","Averse","Ondée","Bruine","Vent chaud","Brise légère","Ciel couvert","Ciel dégagé","Lever de soleil","Coucher de soleil","Rayon de soleil","Nuage de pluie" },
            m = { "Tornade","Ouragan","Cyclone tropical","Typhon","Tempête de neige","Blizzard","Averse de grêle","Orage électrique","Foudre","Éclair en boule","Mousson","Sécheresse","Inondation éclair","Front froid","Front chaud","Anticyclone","Dépression atmosphérique","Isobare","Humidité relative","Point de rosée","Aurore boréale","Halo solaire","Parhelie","Mirage thermique","Vent de sable","Tempête de sable","Poudrerie","Verglas noir","Pluie verglaçante","Nuage lenticulaire","Nuage cumulonimbus","Nuage cirrus","Nuage stratus","Nuage cumulus","Trombe marine","Microrafale","Bombe météorologique","Courant-jet","El Niño","La Niña" },
            h = { "Derecho","Supercellule orageuse","Mésocyclone","Downburst","Haboob","Firenado (tornade de feu)","Nuage mammatus","Nuage a rouleau (shelf cloud)","Nuage nacré","Nuage noctulescent","Inversion thermique","Effet de foehn","Vent catabatique","Vent anabatique","Jet-stream polaire","Oscillation australe","Oscillation nord-atlantique","Vortex polaire","Advection froide","Advection chaude","Radiosonde météorologique","Anémomètre à coupelles","Pluviomètre à auget","Néphoscope","Héliographe","Baromètre à mercure","Hygromètre à cheveu","Satellite météorologique géostationnaire","Radar Doppler météorologique","Modèle de prévision numérique","Gradient barométrique","Cisaillement de vent","Convection atmosphérique","Instabilité atmosphérique","Point de saturation","Enthalpie atmosphérique","Albédo terrestre","Effet de serre atmosphérique","Ceinture de vents alizés","Zone de convergence intertropicale" },
        }},
        { id = "outils", name = "Outils", words = {
            e = { "Marteau","Tournevis","Clé à molette","Pince","Scie","Perceuse","Clou","Vis","Ruban à mesurer","Niveau à bulle","Hache","Pelle","Rateau","Binette","Seau","Échelle","Brouette","Pinceau","Rouleau à peinture","Bâche","Ciseaux","Cutter","Agrafeuse","Colle forte","Ruban adhésif","Corde","Chaîne","Cadenas","Boîte à outils","Gants de travail","Casque de chantier","Lunettes de protection","Masque de protection","Établi","Enclume","Lime à métal","Clé à pipe","Tournevis électrique","Ponceuse","Meuleuse" },
            m = { "Tenaille","Pied-de-biche","Chignole","Visseuse sans fil","Scie sauteuse","Scie circulaire","Scie à métaux","Riveteuse","Compresseur d'air","Cloueuse pneumatique","Niveau laser","Détecteur de métaux (bricolage)","Multimètre","Fer à souder","Décapeur thermique","Pistolet à colle","Truelle","Taloche","Bétonnière","Marteau-piqueur","Diable (chariot)","Palan","Treuil","Cric","Chalumeau","Poste à souder","Rabot électrique","Défonceuse","Toupie (menuiserie)","Mortaiseuse","Établi de menuisier","Serre-joint","Valet d'établi","Équerre de menuisier","Gabarit de perçage","Forêt","Mèche de perceuse","Lame de scie circulaire","Disque de meuleuse","Papier de verre" },
            h = { "Étau d'établi","Filière à fileter","Taraud","Micromètre","Pied à coulisse","Comparateur à cadran","Rectifieuse","Tour à métaux","Fraiseuse","Perceuse à colonne","Poinçonneuse","Cisaille à métaux","Plieuse de tôle","Guillotine à tôle","Soudeuse TIG","Soudeuse MIG","Poste à souder oxyacétylénique","Chalumeau découpeur plasma","Compresseur industriel","Sableuse","Nettoyeur ultrasons","Presse hydraulique","Vérin hydraulique","Clé dynamométrique","Extracteur de roulement","Presse à arbre","Banc de sciage","Déligneuse","Toupie industrielle","Ponceuse à bande","Dégauchisseuse","Raboteuse","Tenonneuse","Mortaiseuse à chaîne","Scie à ruban","Machine à coudre industrielle","Presse à estamper","Matrice de forge","Enclume de forgeron","Marteau-pilon" },
        }},
        { id = "oiseaux", name = "Oiseaux", words = {
            e = { "Moineau","Pigeon","Corbeau","Aigle","Hibou","Chouette","Perroquet","Canard","Cygne","Poule","Coq","Dindon","Colibri","Mésange","Rouge-gorge","Merle","Pie","Cigogne","Flamant rose","Pingouin","Manchot","Autruche","Paon","Faisan","Perdrix","Caille","Pinson","Chardonneret","Hirondelle","Martin-pêcheur","Héron","Cormoran","Mouette","Goéland","Pélican","Toucan","Ara","Cacatoès","Perruche","Canari" },
            m = { "Aigle royal","Faucon pèlerin","Buse variable","Milan noir","Vautour fauve","Condor","Balbuzard","Chouette effraie","Grand-duc","Harfang des neiges","Grue cendree","Ibis","Spatule blanche","Avocette","Échassier","Bécasse","Bécassine","Vanneau","Pluvier","Courlis","Albatros","Fou de Bassan","Pétrel","Puffin","Guillemot","Macareux","Sterne","Grèbe huppé","Foulque","Poule d'eau","Loriot","Huppe fasciée","Pic vert","Pic épeiche","Coucou","Engoulevent","Martinet","Bergeronnette","Tarier","Fauvette" },
            h = { "Kakapo","Kiwi (oiseau)","Casoar","Émeu","Nandou","Secrétaire (oiseau)","Marabout","Calao","Quetzal","Trogon","Cotinga","Manakin","Colibri porte-épée","Colibri huppé","Rollier","Guêpier","Tisserin","Veuve (oiseau)","Combattant varié","Barge rousse","Sterne arctique","Pétrel géant","Albatros hurleur","Fulmar boréal","Frégate (oiseau)","Paille-en-queue","Phaéton","Grèbe esclavon","Plongeon arctique","Harle bièvre","Eider à duvet","Garrot à oeil d'or","Nette rousse","Fuligule milouin","Tadorne de Belon","Ouette d'Égypte","Bernache nonnette","Oie cendrée","Cygne noir","Cygne chanteur" },
        }},
    },
    en = {
        { id = "animals", name = "Animals", words = {
            e = { "Cat","Dog","Horse","Lion","Rabbit","Cow","Duck","Frog","Fish","Bird","Pig","Sheep","Goat","Mouse","Donkey","Hen","Rooster","Turkey","Bee","Butterfly","Snail","Spider","Ant","Turtle","Snake","Bear","Wolf","Fox","Squirrel","Owl","Bat","Hamster","Deer","Boar","Mole","Hedgehog","Pigeon","Crow","Shark","Whale" },
            m = { "Giraffe","Crocodile","Penguin","Dolphin","Kangaroo","Octopus","Flamingo","Bison","Buffalo","Camel","Llama","Panda","Koala","Gorilla","Chimpanzee","Zebra","Hippopotamus","Rhinoceros","Elephant","Ostrich","Peacock","Parrot","Toucan","Jellyfish","Lobster","Crab","Sea lion","Seal","Otter","Badger","Weasel","Ferret","Mink","Lynx","Puma","Jaguar","Hyena","Jackal","Antelope","Gazelle" },
            h = { "Platypus","Axolotl","Pangolin","Nautilus","Tapir","Armadillo","Okapi","Lemur","Monitor lizard","Narwhal","Wombat","Capybara","Fennec fox","Ocelot","Emperor penguin","Golden eagle","Vulture","Ibis","Hummingbird","Salamander","Iguana","Chameleon","Scorpion","Centipede","Earthworm","Starfish","Sea urchin","Eel","Swordfish","Manta ray","Buzzard","Falcon","Marten","Genet","Marmot","Shrew","Dormouse","Anteater","Kinkajou","Quokka" },
        }},
        { id = "jobs", name = "Jobs", words = {
            e = { "Doctor","Firefighter","Police officer","Baker","Dentist","Nurse","Pilot","Postman","Cook","Teacher","Hairdresser","Waiter","Salesperson","Cashier","Driver","Gardener","Carpenter","Electrician","Plumber","Painter","Butcher","Florist","Farmer","Shepherd","Fisherman","Sailor","Soldier","Lawyer","Judge","Secretary","Actor","Singer","Dancer","Writer","Journalist","Photographer","Courier","Librarian","Guide","Translator" },
            m = { "Architect","Master carpenter","Surgeon","Editor (writing)","Cameraman","Accountant","Geologist","Diplomat","Vet","Pharmacist","Engineer","Notary","Insurer","Banker","Trader","Designer","Illustrator","Screenwriter","Director","Producer","Researcher","Biologist","Chemist","Physicist","Statistician","Urban planner","Historian","Archaeologist","Anthropologist","Sociologist","Psychologist","Psychiatrist","Physiotherapist","Osteopath","Speech therapist","Occupational therapist","Midwife","Paramedic","Customs officer","Court clerk" },
            h = { "Astrophysicist","Entomologist","Paleontologist","Cartographer","Cryptologist","Epidemiologist","Police superintendent","Sophrologist","Puppeteer","Luthier","Sommelier","Taxidermist","Watchmaker","Hatter","Tanner","Stained-glass artist","Cabinetmaker","Blacksmith","Cooper","Glassblower","Cobbler","Saddler","Coppersmith","Tinsmith","Basket weaver","Felt maker","Weaver","Art restorer","Numismatist","Volcanologist","Seismologist","Meteorologist","Oceanographer","Ornithologist","Herpetologist","Malacologist","Papyrologist","Heraldist","Campanologist","Sinologist" },
        }},
        { id = "sports", name = "Sports", words = {
            e = { "Football","Tennis","Swimming","Skiing","Boxing","Golf","Rugby","Judo","Cycling","Basketball","Karate","Gymnastics","Athletics","Marathon","Petanque","Table tennis","Bowling","Darts","Skating","Surfing","Sailing","Climbing","Hiking","Yoga","Weightlifting","Ballroom dancing","Trampoline","Skateboarding","Rollerskating","Baseball","Cricket","Billiards","Horseshoes","Archery","Wrestling","Bowls","Running","Frisbee","Ice hockey","Karting" },
            m = { "Fencing","Rowing","Badminton","Horse riding","Diving","Handball","Biathlon","Curling","Volleyball","Triathlon","Water polo","Taekwondo","Aikido","Capoeira","Cross-fit","Snowboarding","Water skiing","Trick riding","Trial","Motocross","Junior bobsleigh","Rink hockey","Cyclocross","Duathlon","Decathlon","Heptathlon","Nordic walking","Canoe-kayak","Rafting","Paragliding","Hang gliding","Base jumping","Platform diving","Synchronized swimming","Rhythmic gymnastics","Sport shooting","Artistic fencing","Roller hockey","Unihockey","Netball" },
            h = { "Bobsleigh","Pentathlon","Basque pelota","Kitesurfing","Luge","Lacrosse","Squash","Skeleton","Sumo","Polo","Kabaddi","Sepak takraw","Hurling","Jai alai","Skijoring","Bandy","Broomball","Cane fighting","Savate","Pankration","Sambo","Kendo","Iaido","Kyudo","Jujitsu","Krav maga","Speed skiing","Orienteering","Triple jump","Hammer throw","Discus throw","Pole vault","Ultra-trail running","Fat biking","Ski mountaineering","Dog sledding","Tug of war","Water jousting","Underwater hockey","Footgolf" },
        }},
        { id = "food", name = "Food", words = {
            e = { "Pizza","Cake","Bread","Cheese","Soup","Ice cream","Salad","Pancake","Spaghetti","Omelette","Apple","Banana","Orange","Strawberry","Grape","Carrot","Tomato","French fries","Hamburger","Sandwich","Rice","Egg","Butter","Milk","Yogurt","Jam","Honey","Chocolate","Candy","Cookie","Chicken","Ham","Sausage","Fish sticks","Croissant","Baguette","Pie","Muffin","Popcorn","Pickle" },
            m = { "Quiche","Fondue","Ratatouille","Couscous","Risotto","Paella","Meringue","Artichoke","Sushi","Lasagna","Snails","Foie gras","Sauerkraut","Tartare","Ceviche","Gazpacho","Falafel","Hummus","Tempura","Dim sum","Curry","Naan","Tacos","Guacamole","Empanada","Gnocchi","Ravioli","Pesto","Tiramisu","Panna cotta","Creme brulee","Rum baba","Financier","Macaron","Nougat","Calisson","Kouign-amann","Canele","Far breton","King cake" },
            h = { "Bourguignon","Mille-feuille","Bouillabaisse","Cassoulet","Profiteroles","Blanquette","Gougeres","Croquembouche","Tarte Tatin","Vichyssoise","Consomme","Veloute","Tartiflette","Aligot","Pot-au-feu","Andouillette","Black pudding","Rillettes","Duck confit","Tapenade","Baklava","Pavlova","Souffle","Vacherin","Charlotte","Kouglof","Bread pudding","Clafoutis","Puff pastry","Pate en croute","Terrine","Quenelle","Vol-au-vent","Chicken fricassee","Navarin","Fricassee","Estouffade","Rabbit civet","Marmalade","Stewed fruit" },
        }},
        { id = "places", name = "Places", words = {
            e = { "Beach","Mountain","Forest","Station","Airport","Market","Church","School","Hospital","Castle","Farm","Village","City","Park","Swimming pool","Cinema","Restaurant","Hotel","Zoo","Museum","Bridge","Tunnel","Road","Sidewalk","Garden","Cemetery","Town hall","Bank","Post office","Supermarket","Bakery","Pharmacy","Garage","Factory","Construction site","Campsite","Shelter","Police station","Fire station","Playground" },
            m = { "Desert","Volcano","Lighthouse","Mosque","Fjord","Monastery","Stadium","Library","Cave","Harbor","Waterfall","Cliff","Marsh","Meadow","Valley","Hill","Plateau","Canyon","Oasis","Steppe","Tundra","Savanna","Jungle","Iceberg","Glacier","Reef","Lagoon","Delta","Archipelago","Peninsula","Synagogue","Temple","Hindu pagoda","Cathedral","Basilica","Chapel","Abbey","Fortress","Citadel","Moat" },
            h = { "Catacombs","Atoll","Pagoda","Estuary","Bunker","Labyrinth","Megalith","Cistern","Crypt","Leprosarium","Necropolis","Ziggurat","Amphitheater","Aqueduct","Roman baths","Caravanserai","Kasbah","Souk","Medina","Minaret","Ossuary","Mausoleum","Cenotaph","Observatory","Planetarium","Herbarium","Tropical greenhouse","Lava field","Fumarole","Solfatara","Sinkhole","Chasm","Reg desert","Erg desert","Hamada","Wadi","Playa","Salt flat","Fjeld","Glacial cirque" },
        }},
        { id = "objects", name = "Objects", words = {
            e = { "Key","Chair","Lamp","Phone","Bag","Book","Clock","Umbrella","Ball","Hammer","Table","Plate","Glass","Fork","Knife","Spoon","Pot","Pan","Cushion","Blanket","Mirror","Brush","Comb","Soap","Towel","Suitcase","Belt","Wallet","Glasses","Watch","Pen","Pencil","Eraser","Ruler","Scissors","Glue","Stapler","Envelope","Stamp","Postcard" },
            m = { "Microscope","Telescope","Accordion","Hourglass","Compass","Watering can","Swing","Fan","Trampoline","Harmonica","Compass (magnetic)","Binoculars","Magnifying glass","Candlestick","Lantern","Alarm clock","Scale","Thermometer","Barometer","Pressure gauge","Easel","Palette","Paintbrush","Wood chisel","Plane","Anvil","Vise","Drill","Saw","File","Loom","Spindle","Spinning wheel","Bobbin winder","Sundial","Weather vane","Windmill","Well","Plow","Sickle" },
            h = { "Sextant","Alembic","Tripod","Corkscrew","Bellows","Rain gauge","Set square","Bottle opener","Astrolabe","Metronome","Theodolite","Seismograph","Foucault pendulum","Moon dial","Water clock","Kaleidoscope","Stereoscope","Zoetrope","Praxinoscope","Gramophone","Telegraph","Optical sextant","Treadle spinning wheel","Bobbin winder frame","Shoehorn","Fire poker","Forge bellows","Jackhammer","Spirit level","Plumb line","Marine compass","Octant","Gnomon","Anemometer","Hygrometer","Altimeter","Handheld sonar","Radiometer","Spectroscope","Polarimeter" },
        }},
        { id = "nature", name = "Nature", words = {
            e = { "Sun","Cloud","Tree","River","Flower","Rain","Rainbow","Rock","Star","Wave","Moon","Sky","Grass","Leaf","Branch","Root","Seed","Mushroom","Moss","Sand","Hill","Forest","Lake","Island","Snow","Ice","Wind","Storm","Lightning","Drizzle","Dew","Fog","Stream","Marsh","Meadow","Bush","Fern","Ivy","Cactus","Bamboo" },
            m = { "Tornado","Northern lights","Stalactite","Glacier","Thunderbolt","Swamp","Sand dune","Volcano","Geyser","Whirlpool","Stalagmite","Cliff","Canyon","Delta","Estuary","Coral reef","Tundra","Savanna","Mangrove","Peat bog","Meander","Waterfall","Cave","Melting iceberg","Ice floe","Avalanche","Hurricane","Cyclone","Typhoon","Monsoon","Moonbow","Sun halo","Mirage","Bioluminescence","Photosynthesis","Pollination","Symbiosis","Ecosystem","Biotope","Permafrost" },
            h = { "Eclipse","Moraine","Sea spray","Crevasse","Confluence","Epiphyte","Karst","Silt","Atoll","Serac","Fumarole","Solfatara","Sinkhole","Limestone pavement","Drumlin","Esker","Loess","Playa","Salt flat","Fjeld","Nebula","Natural aerosol","Thermokarst","Paleosol","Varve","Tillite","Regolith","Sapropel","Travertine","Geode","Fulgurite","Tektite","Permafrost layer","Solifluction","Cryoturbation","Nivation","Wind deflation","Corrasion","Bioturbation","Halocline" },
        }},
        { id = "activities", name = "Activities", words = {
            e = { "Run","Swim","Sing","Dance","Paint","Cook","Read","Garden","Jump","Draw","Write","Walk","Smile","Sleep","Eat","Drink","Fly a plane","Drive","Fish","Hunt","Clean","Sweep","Wash","Fold","Sew","Iron (clothes)","Build","Repair","Paint a wall","Vacuum","Plant","Water","Harvest","Pick","Stack","Carry","Push","Pull","Throw","Catch" },
            m = { "Knit","Rock climb","Surf","Meditate","Sculpt","Juggle","Dive","Camp","Tow","Blow","Skate","Ski","Row","Paddle","Rope climb","Cycle","Ride a horse","Do archery","Sail","Kayak","Do yoga","Box","Fence","Do pottery","Weave","Embroider","Spin wool","Forge","Blow glass","Carve stone","Negotiate","Debate","Teach","Conduct an orchestra","Compose","Improvise","Choreograph","Direct a play","Direct a film","Stage a show" },
            h = { "Distil","Set a gemstone","Map","Ferment","Plough","Enamel","Calligraph","Spelunk","Balance","Scarify","Tan leather","Chase metal","Do marquetry","Restore a painting","Calibrate an instrument","Herborize","Taxidermy an animal","Make stained glass","Shoe a horse","Winnow grain","Distill spirits","Age cheese","Harvest grapes","Tread grapes","Trim vines","Graft a tree","Prune a bonsai","Practice falconry","Train a raptor","Walk a tightrope","Ride a unicycle","Juggle torches","Do ventriloquism","Fold origami","Do marquetry work","Apply gilding","Restore an old book","Bind a book","Do metal inlay","Do damascening" },
        }},
        { id = "transport", name = "Transport", words = {
            e = { "Car","Bike","Bus","Train","Airplane","Boat","Motorcycle","Truck","Taxi","Tram","Subway","Scooter","Kick scooter","Skateboard","Roller skates","Cart","Carriage","Sleigh","Airship","Delivery van","Police car","Ambulance","Fire truck","Pedal boat","Canoe","Kayak","Sailboat","Ferry","Cable car","Funicular","Hearse","Van","RV","Trailer","Stagecoach","Rickshaw","Tuk-tuk","Vespa","Quad bike","Electric scooter" },
            m = { "Helicopter","Submarine","Ocean liner","Three-masted sailboat","Zeppelin","Hang glider","Paraglider","Hot air balloon","Dog sled","Handcar","Steam locomotive","Heritage tram","Gondola lift","Ski tow","Hovercraft","Seaplane","Glider","Ultralight aircraft","Snowmobile","Jet ski","Dump truck","Mobile crane","Bulldozer","Backhoe loader","Forklift","Semi-trailer truck","Tanker wagon","Barge","Punt","Motor launch","Trimaran","Catamaran","Kite-towed board","Land yacht","Amphibious vehicle","Coach","Minibus","Sedan","Station wagon","Convertible" },
            h = { "Aerotrain","Rigid airship","Nuclear submarine","Icebreaker","Container ship","Oil tanker","Factory ship","Bathyscaphe","Space shuttle","Rocket","Lunar module","Mars rover","Military zeppelin","Autogyro","Flying wing","Cargo plane","Air tanker","Snowplow","Motorized handcar","Sleeper train car","Dining car","High-speed train","Monorail","Rack railway","Alpine cable car","Sail sledge","Transport bobsled","Ox cart","Palanquin","Motorized wheelbarrow","Tracked vehicle","Half-track","Military amphibian","Hydrofoil","Racing trimaran","Polar sailboat","Whaleboat","Pocket submarine","Lunar rover","Space capsule" },
        }},
        { id = "body", name = "Human body", words = {
            e = { "Head","Hand","Foot","Eye","Nose","Mouth","Ear","Arm","Leg","Finger","Knee","Elbow","Shoulder","Back","Belly","Neck","Chin","Eyebrow","Eyelash","Tooth","Hair","Nail","Ankle","Wrist","Heel","Belly button","Cheek","Forehead","Lip","Tongue","Skin","Muscle","Bone","Heart","Lung","Brain","Skeleton","Blood","Vein","Thumb" },
            m = { "Liver","Stomach","Kidney","Intestine","Bladder","Spine","Rib","Collarbone","Tendon","Ligament","Pupil","Retina","Iris","Eardrum","Larynx","Pharynx","Trachea","Bronchi","Diaphragm","Spleen","Pancreas","Gallbladder","Aorta","Artery","Nerve","Cartilage","Spinal cord","Thyroid gland","Pituitary gland","Hair follicle","Fingerprint","Cuticle","Armpit","Nape","Temple","Cheekbone","Dimple","Scar","Mole","Wrinkle" },
            h = { "Ureter","Sphincter","Peritoneum","Endocardium","Myocardium","Synapse","Neuron","Hemoglobin","Lymph","Lymph node","Thymus","Cerebral cortex","Cerebellum","Hypothalamus","Medulla oblongata","Uvula","Tonsil","Epiglottis","Meninges","Sclera","Cornea","Lens (eye)","Choroid","Ear ossicle","Cochlea","Placenta","Fontanelle","Shoulder blade","Sternum","Humerus","Femur","Kneecap","Tibia","Fibula","Radius (bone)","Ulna","Vertebra","Pelvis","Windpipe","Appendix" },
        }},
        { id = "clothing", name = "Clothing", words = {
            e = { "Shirt","Pants","Dress","Skirt","Shoe","Sock","Hat","Coat","Jacket","Sweater","Shorts","Swimsuit","Glove","Scarf","Beanie","Belt","Tie","Boot","Sandal","Pajamas","Apron","Cap","Leggings","Tights","Jeans","T-shirt","Vest","Raincoat","Underwear","Tank top","Shawl","Slipper","Bib","Overalls","Bathrobe","Rain boots","Mitten","Suspenders","Bow tie","Bridal veil" },
            m = { "Kimono","Sari","Kilt","Poncho","Sombrero","Turban","Three-piece suit","Tuxedo","Toga","Cape","Balaclava","Ski suit","Wetsuit","Bulletproof vest","Armor","Chasuble","Cassock","Military uniform","Lab coat","Surgical gown","Judo gi","Flamenco dress","Sarong","Boubou","Djellaba","Hijab","Bowler hat","Top hat","Corset","Crinoline","Gaiters","Rain cape","Work overalls","Space suit","Leotard","Tutu","Dancer's tights","Stage costume","Dressing gown","Scottish kilt" },
            h = { "Ballet pointe shoe","Wimple","Ruff collar","Farthingale","Hoop petticoat","Frock coat","Tailcoat","Morning coat","Top hat (formal)","Bicorne hat","Tricorne hat","Pickelhaube","Great helm","Chainmail","Gauntlet","Armor greaves","Braies","Peplos","Roman toga","Chlamys","Clogs","Galoshes (old style)","Vintage espadrilles","Opera hat","Detachable collar","Shirt front","Leather gaiters","Fur coat","Fur stole","Fur muff","Parasol","Lorgnette","Monocle","Pince-nez","Geisha headband","Obi sash","Yukata robe","Hakama trousers","Zori sandals","Geta sandals" },
        }},
        { id = "music", name = "Music", words = {
            e = { "Guitar","Piano","Violin","Drums","Flute","Trumpet","Drum","Microphone","Headphones","Radio","Singer","Musician","Concert","Musical note","Sheet music","Bell","Tambourine","Maracas","Triangle (instrument)","Xylophone","Harp","Clarinet","Saxophone","Trombone","Organ","Accordion","Ukulele","Banjo","Cymbal","Metronome","Choir","Karaoke","Vinyl record","Speaker","Conductor's baton","Music stand","Music box","Whistle","Jingle bell","Keyboard" },
            m = { "Cello","Double bass","Oboe","Bassoon","French horn","Tuba","Bagpipes","Didgeridoo","Sitar","Kora","Balalaika","Mandolin","Lute","Hurdy-gurdy","Cimbalom","Marimba","Vibraphone","Celesta","Harpsichord","Barrel organ","Theremin","Synthesizer","Drum machine","Mixing console","Tuning fork","Conductor","Composer","Librettist","Choir member","Soloist","Symphony","Concerto","Opera","Operetta","Brass band","Big band","String quartet","Jazz trio","Gospel choir","Philharmonic orchestra" },
            h = { "Theorbo","Medieval vielle","Serpent (instrument)","Ophicleide","Sackbut","Crumhorn","Scottish bagpipes","Duduk","Erhu","Shamisen","Koto","Guzheng","Pipa","Santoor","Oud","Bouzouki","Charango","Venezuelan cuatro","Berimbau","Steel drum","Handpan","Glass harmonica","Ondes Martenot","Basso continuo","Counterpoint","Fugue","Solfege","Neume","Tablature","Reference pitch fork","Luthier at work","Clavichord","Spinet","Virginal","Regal organ","Hurdy-gurdy organistrum","Cittern","Archlute","Mandora","Rebec" },
        }},
        { id = "technology", name = "Technology", words = {
            e = { "Computer","Mobile phone","Television","Tablet","Computer mouse","Keyboard","Screen","Printer","Camera","VR headset","Game console","Controller","USB drive","Charger","Earphones","Smart speaker","Robot","Drone","Camcorder","Webcam","Wifi router","Battery","LED bulb","Switch","Power outlet","Cable","Antenna","Satellite","Microchip","SIM card","Smartwatch","E-reader","Scanner","Photocopier","Fax machine","Walkie-talkie","Remote control","Timer","Smoke detector","Robot vacuum" },
            m = { "Processor","Motherboard","Hard drive","Server","Neural network","Circuit board","Transistor","Diode","Capacitor","Resistor","3D printer","3D scanner","Robotic arm","Motion sensor","Touchscreen","Augmented reality","VR headset (advanced)","Artificial intelligence","Algorithm","Database","Fiber optic cable","Modem","UPS unit","Solar panel","Wind turbine","Fuel cell","Lithium battery","RFID chip","Barcode","Biometric scanner","Exoskeleton","Bionics","Nanorobot","Braille printer","Voice synthesizer","Machine translator","Voice assistant","Noise-cancelling headphones","Haptic controller","Flight simulator" },
            h = { "Semiconductor","Superconductor","Qubit","Quantum computer","Deep neural network","Turing machine","Cellular automaton","Integrated circuit","Micro-inverter","Particle accelerator","Cyclotron","Synchrotron","Mass spectrometer","Interferometer","Laser gyroscope","Infrared sensor","Particle detector","Fusion reactor","Fission reactor","Centrifuge","Faraday cage","Tesla coil","Van de Graaff generator","Oscilloscope","Spectrum analyzer","Operational amplifier","Analog-to-digital converter","Photodiode","Excimer laser","Waveguide","Metamaterial","Photonic crystal","Biochip","Neuroprosthesis","Brain-computer interface","Carbon nanotube","Graphene","3D bioprinting","Surgical robot","Observation satellite" },
        }},
        { id = "space", name = "Space", words = {
            e = { "Rocket","Astronaut","Planet","Moon","Star","Sun","Earth","Comet","Satellite","Space shuttle","Space helmet","Space suit","Space station","Meteorite","Black hole","Galaxy","Milky Way","Constellation","Telescope","Observatory","Mars","Jupiter","Saturn","Venus","Mercury (planet)","Uranus","Neptune","Pluto","Asteroid","Nebula","Orbit","Moon crater","Saturn's rings","Alien","Flying saucer","Moon base","Space rover","Satellite dish","Multistage rocket","Reentry capsule" },
            m = { "Wormhole","Supernova","White dwarf","Neutron star","Solar system","Asteroid belt","Kuiper belt","Oort cloud","Exoplanet","Habitable zone","Gravity","Weightlessness","Cosmic ray","Solar wind","Polar aurora","Solar eclipse","Lunar eclipse","Earth's tides","Earth's rotation","Planetary revolution","Space probe","Lunar lander","Space robotic arm","Space solar panel","Pressure suit","Space diving suit","Reusable rocket","Heavy-lift launcher","Launch tower","Launch pad","Radio telescope","Space telescope","Space interferometer","Stellar spectrograph","Space atomic clock","Star compass","Star chart","Digital planetarium","Space flight simulator","Mission control" },
            h = { "Quasar","Pulsar","Magnetar","Supermassive black hole","Dark matter","Dark energy","Cosmic microwave background","Big Bang","Gravitational singularity","Event horizon","Gravitational lens","Brown dwarf","Red giant","Blue hypergiant","Globular cluster","Galaxy cluster","Cosmic filament","Cosmic void","Accretion disk","Relativistic jet","Gravitational wave","Higgs boson","Antimatter","Gamma-ray photon","Cosmic X-ray","Interstellar probe","Solar sail","Ion propulsion","Nuclear thermal propulsion","Space cryogenics","Terraforming","Rotating space habitat","Space elevator","Lagrange point","Gravity assist maneuver","Launch window","Geostationary orbit","Polar orbit","Atmospheric reentry","Heat shield" },
        }},
        { id = "fantasy", name = "Fantasy", words = {
            e = { "Dragon","Witch","Ghost","Vampire","Fairy","Unicorn","Haunted castle","Magic wand","Wizard","Monster","Werewolf","Zombie","Skeleton","Mummy","Giant","Dwarf","Elf","Troll","Goblin","Ogre","Cauldron","Flying broom","Crystal ball","Magic potion","Flying carpet","Genie in a lamp","Magic sword","Shield","Magic ring","Spellbook","Invisibility cloak","Pointed hat","Magic crystal","Amulet","Spell","Curse","Magical familiar","Magic portal","Treasure chest","Treasure map" },
            m = { "Mermaid","Centaur","Griffin","Phoenix","Hydra","Cyclops","Minotaur","Sphinx","Pegasus","Chimera","Kraken","Basilisk","Golem","Necromancer","Black knight","Bard","Druid","Paladin","Elf ranger","Archmage","Dimensional portal","Mana crystal","Enchanted scroll","Rune sword","Enchanted armor","Ring of power","Magic orb","Talisman","Ancient runes","Summoning circle","Dark fortress","Wizard tower","Elf village","Enchanted forest","Cursed swamp","Volcano of shadows","Gate to the underworld","Lost city","Forgotten temple","Ancient ruins" },
            h = { "Lich","Demigod","Titan","Winged chimera","Wyvern","Hippogriff","Kelpie","Banshee","Selkie","Djinn","Rakshasa","Yokai","Oni","Kappa","Magical tanuki","Baku (dream eater)","Naga","Garuda","Manticore","Cockatrice","Homunculus","Living gargoyle","Elemental spirit","Fire elemental","Water elemental","Earth elemental","Air elemental","Divine avatar","Sacred relics","Philosopher's stone","Interdimensional portal","Ancient magic seal","Ancestral curse","Prophecy","Mystic oracle","Spectral guardian","Wandering soul","Poltergeist","Fantasy bounty hunter","Legendary alchemist" },
        }},
        { id = "movies", name = "Movies and TV", words = {
            e = { "Camera","Movie screen","Popcorn","Movie ticket","Cinema seat","Projector","Director","Actor","Actress","Script","Clapperboard","Boom microphone","Movie costume","Makeup","Film set","Storyboard","Trailer","Credits","TV remote","TV antenna","Flat screen TV","Game console (living room)","DVD","Game controller","Cartoon","Superhero","Supervillain","Stunt","Special effects","Film reel","Movie theater","Recliner seat","Candy dispenser","Movie poster","Hollywood star (sidewalk)","Security camera","Filming drone","Camera crane","Green screen","Boom pole" },
            m = { "Cinematographer","Film editor","Sound engineer","Voice actor","Stunt performer","Puppeteer (film)","Set designer","Costume designer","Special effects makeup artist","Executive producer","Screenwriter","Film composer","Colorist","Boom operator","Assistant director","Script doctor","Casting director","Movie premiere","Film festival","Red carpet","Film award","Oscar nomination","Digital visual effects","Stop-motion animation","Motion capture","Blue screen","Camera dolly shot","Steadicam","Camera crane shot","Filming drone shot","TV series","TV season","Pilot episode","Spin-off show","Reboot","Documentary","Short film","Feature film","Silent film","Black and white film" },
            h = { "Optical anamorphosis","Kinetoscope","Zoetrope","Praxinoscope","Camera obscura","Film stock","Film development","Negative cutter","Digital color grading","Production designer","Set dresser","Prop master","Unit production manager","Casting director (senior)","Dialogue coach","Stunt coordinator","Stunt team lead","Practical effects technician","Animatronics","Animatronic puppet","Matte painting","Rotoscoping","Advanced chroma key","Performance capture","3D facial scanning","Digital rendering","Color timing","5.1 sound mixing","Foley artistry","Foley artist","Lip sync","Subtitling","Voice dubbing","International distribution","Film rating classification","Film archive institute","Old film restoration","Film archive","70mm screening","Outdoor cinema" },
        }},
        { id = "celebrations", name = "Celebrations", words = {
            e = { "Christmas tree","Present","Santa Claus","Birthday candle","Birthday cake","Party balloon","Confetti","Fireworks","Garland","Halloween pumpkin","Halloween costume","Candy","Easter egg","Easter bunny","Wedding flowers","Engagement ring","Wedding cake","Invitation card","Candle","Champagne","Streamers","Party hat","Carnival mask","Party favors","Firecracker","Shooting star (decor)","Advent calendar","Christmas wreath","Christmas stocking","Santa's sleigh","Reindeer","Snowman","Christmas ornament","Christmas bell","Stocking","Christmas turkey","Yule log cake","Candlestick","Party lantern","Party flag" },
            m = { "Bonfire celebration","Carnival float","Carnival parade","Wedding confetti","Bridal veil","Wedding ring","Bridesmaid","Best man","Cake slice","Baptism","Communion","Bar mitzvah","Graduation diploma","Graduation gown","Graduation cap","Torchlight procession","Masquerade ball","New Year's Eve dinner","New Year countdown","New Year party favors","Chinese lantern","Chinese New Year dragon","National fireworks display","National flag","Fairy light garland","Christmas window display","Christmas market","Easter chocolate","Easter egg hunt","Easter basket","Witch costume","Trick or treat","Pumpkin carving","Fake spider web","Halloween skeleton decor","Halloween graveyard decor","Parade brass band","Flower float","Paper confetti","Christmas cracker" },
            h = { "Pinata","Diwali garland","Diwali oil lamp","Rangoli pattern","Hanukkah lantern","Nine-branched menorah","Hanukkah dreidel","Spring festival cake","Lion dance","Dragon dance","Traditional Chinese firecracker","Red envelope (gift money)","Mardi Gras costume","Venetian mask","Rio carnival float","Carnival samba dance","Rio carnival confetti","Lantern festival","Floating lantern","Lantern boat","Mid-autumn festival","Mooncake","May Day festival","Lily of the valley sprig","Epiphany cake","King cake charm","Advent wreath","Advent candle","Christmas gingerbread man","Nativity figurine","Nativity scene","Star of Bethlehem (decor)","Holly garland","Mistletoe bunch","Sinterklaas costume","Gift clog","Gingerbread man","Gingerbread village","Candy cane","Sleigh bell" },
        }},
        { id = "school", name = "School", words = {
            e = { "Backpack","Notebook","Pen","Pencil","Eraser","Ruler","Blackboard","Chalk","School desk","Pencil case","Textbook","Classroom","Recess","Schoolyard","Cafeteria","School bus","School uniform","Report card","Homework","Exam","Exam paper","Grade","Diploma","Calculator","Geometry compass","Set square","Pencil sharpener","Marker","Highlighter","Binder","School planner","School locker","School bell","Playground game","Colored chalk","Slate","Globe","World map (classroom)","Skeleton (biology class)","School microscope" },
            m = { "Lecture hall","Science lab","Computer room","School gym","School library","School nurse's office","Principal","School counselor","Hall monitor","Homeroom teacher","Class schedule","Parent-teacher meeting","Grade repetition","Career guidance","Work placement","School trip","School exchange trip","Language exchange","Tutoring session","Homework assignment","Back to school","School holidays","High school diploma exam","Middle school certificate","Entrance exam","Essay writing","Oral presentation","Slideshow presentation","Group project","School club","School orchestra","School sports team","School newspaper","School radio","Student common room","Boarding school","Boarding house","School lunch tray","Vending machine (school)","School photocopier" },
            h = { "University lecture hall","Thesis defense room","Thesis committee","Master's thesis","Doctoral dissertation","Thesis advisor","University research lab","Scholarship","Erasmus exchange","Academic conference","Scientific publication","Peer review committee","Academic plagiarism","Cheat sheet","Student hazing ritual","Student association","Alumni association","School honor track","Prep school program","Elite grande ecole","Teacher training college","Teaching qualification exam","Research supervision qualification","Postdoctoral fellowship","Academic sabbatical","University chair position","Faculty dean","Academic inspector general","School district inspector","Montessori pedagogy","Freinet pedagogy","Distance learning","Flipped classroom","Interactive whiteboard","Massive open online course","Professional certification","Prior learning validation","Continuing education","Work-study apprenticeship","Doctoral school" },
        }},
        { id = "house", name = "House", words = {
            e = { "Table","Chair","Bed","Sofa","Wardrobe","Shelf","Fridge","Oven","Sink","Shower","Bathtub","Toilet","Door","Window","Staircase","Rug","Curtain","Cushion","Pillow","Comforter","Desk lamp","Television (living room)","Remote control","Cupboard","Dresser","Drawer","Coat hanger","Broom","Vacuum cleaner","Mop","Trash can","Mailbox","Doorbell","House key","Roof","Fireplace","Garage","House garden","Fence","Gate" },
            m = { "Laundry room","Washing machine","Clothes dryer","Dishwasher","Microwave oven","Toaster","Kettle","Coffee maker","Blender","Food processor","Water heater","Boiler","Radiator","Air conditioner","Ceiling fan","Blind","Roller shutter","Glass roof","Mezzanine","Attic","Cellar","Basement","Terrace","Sunroom","Pergola","Balcony","Garden swing set","Lawn mower","Wheelbarrow","Rake","Garden watering can","Garden greenhouse","Compost bin","Barbecue grill","Garden pool","Outdoor hot tub","Garden shed","Garden hut","House well","Garden fountain" },
            h = { "Trash chute","Home dumbwaiter","Private elevator","Home cold room","Wine cellar","Pantry room","Professional laundry room","Utility room","Home automation system","Smart thermostat","Carbon monoxide detector","Security roller shutter","Wall safe","Home alarm system","Video intercom","Smart lock","Bioclimatic shading","Skylight","Workshop glass roof","Exposed roof frame","Main beam","Floor joist","Roof rafter","Roof ridge","Gutter","Downspout","Storm drain","Septic tank","Soakaway pit","Rainwater tank","Solar thermal panel","Heat pump","Heat recovery unit","Dual-flow ventilation system","Soundproofing","Thermal insulation","Vapor barrier","Exterior cladding","Facade render","Architectural cornice" },
        }},
        { id = "toys", name = "Toys", words = {
            e = { "Doll","Teddy bear","Balloon","Kite","Spinning top","Yo-yo","Puzzle","Dominoes","Building blocks","Toy car","Toy train","Toy robot","Puppet","Jump rope","Marble","Playing cards","Checkers","Chessboard","Toy scooter","Tricycle","Doll stroller","Dollhouse","Toy farm","Toy chest","Balloon (party)","Slide","Swing","Sandbox","Water gun","Soap bubbles","Toy instrument","Toy drum","Toy xylophone","Stuffed rabbit","Stuffed dog","Action figure","Toy castle","Modeling clay","Toy kaleidoscope","Toy music box" },
            m = { "Rocking horse","Gyroscopic top","Professional yo-yo","Jack-in-the-box","Wooden brain teaser","Meccano set","Wooden building planks","Marble run","Ball pit slide","Bouncy castle","Stunt kite","Toy drone","Remote-control robot","RC car","RC boat","Toy airplane","Toy rocket","Marionette","Hand puppet","Puppet theater","Board game","Toy role-play set","Action figure (articulated)","Toy diorama","Model kit","Scale model","Electric train set","Toy electric circuit","Toy magnifying glass","Toy microscope","Toy telescope","Toy globe","Construction set","Giant building blocks","Throwing top","Hula hoop","Diabolo","Cup-and-ball toy","Dart game","Nerf dart" },
            h = { "Mechanical automaton","Antique music box","Antique porcelain doll","Vintage rocking horse","Toy zoetrope","Toy praxinoscope","Shadow puppet theater","Magic lantern","Antique game of goose","Wood-turned spinning top","Antique skittles set","Historical diorama","Antique ship model","Vintage model airplane","Miniature steam train","Elaborate miniature railway layout","Balinese shadow puppet","Javanese rod puppet","Russian nesting doll","Singing top","Wind-up spring toy","Crank-operated automaton","Handcrafted kaleidoscope","Antique toy stereoscope","Retro optical toy","Antique patience puzzle","Iron puzzle","Complex 3D puzzle","Handcrafted cup-and-ball","Professional diabolo","Traditional Japanese kite","Indian fighter kite","Competition spinning top","Medieval jointed toy","Antique lead figurine","Toy soldier (lead)","Tinplate toy","Tin wind-up car","Vintage tin robot","Miniature carousel" },
        }},
        { id = "ocean", name = "Ocean", words = {
            e = { "Fish","Shark","Whale","Dolphin","Octopus","Starfish","Crab","Seashell","Wave","Beach","Boat","Sailboat","Anchor","Fishing net","Lighthouse","Sand","Palm tree","Buoy","Diving mask","Snorkel","Diving fins","Beach towel","Beach umbrella","Sandcastle","Scallop","Lobster","Shrimp","Oyster","Mussel","Seaweed","Seagull","Pelican","Deserted island","Reef","Submarine","Pearl","Coral","Jellyfish","Sea turtle","Seal" },
            m = { "Hammerhead shark","Whale shark","Orca","Sperm whale","Narwhal","Sea lion","Walrus","Manatee","Clownfish","Pufferfish","Seahorse","Giant octopus","Squid","Cuttlefish","Stingray","Sea eel","Swordfish","Tuna","Barracuda","Sea piranha","Volcanic island","Coral atoll","Turquoise lagoon","Ocean trench","Ocean current","High tide","Low tide","Storm wave","Tsunami","Tropical cyclone","Fishing boat","Trawler","Cargo ship","Oil tanker","Racing sailboat","Catamaran","Scuba diving","Diving tank","Wetsuit","Regulator (diving)" },
            h = { "Abyss","Mariana Trench","Lanternfish","Viperfish","Giant squid","Dumbo octopus","Giant tube worm","Yeti crab","Pistol shrimp","Black coral","Hydrothermal vent","Chemosynthetic bacteria","Abyssal sea cucumber","Anglerfish","Hatchetfish","Goblin shark","Frilled shark","Beluga whale","Dugong","Fur seal","Bathyscaphe","Exploration submersible","Side-scan sonar","Marine sediment coring","Oceanographic buoy","Humboldt current","Ocean gyre","Upwelling","Thermocline","Halocline","Fringing reef","Barrier reef","Coastal mangrove","Seagrass meadow","Bathyal zone","Abyssal zone","Hadal zone","Bioluminescent plankton","Chambered nautilus","Paper nautilus" },
        }},
        { id = "weather", name = "Weather", words = {
            e = { "Sun","Rain","Cloud","Snow","Wind","Storm","Lightning","Thunder","Rainbow","Fog","Hail","Black ice","Heatwave","Cold snap","Umbrella","Raincoat","Rain boots","Thermometer","Weather vane","Dark cloud","Blue sky","Starry sky","Morning dew","Frost","Hoarfrost","Wind gust","Snowflake","Snowman","Snowball fight","Rain shower","Downpour","Drizzle","Warm wind","Light breeze","Overcast sky","Clear sky","Sunrise","Sunset","Sunbeam","Rain cloud" },
            m = { "Tornado","Hurricane","Tropical cyclone","Typhoon","Snowstorm","Blizzard","Hailstorm","Thunderstorm","Lightning bolt","Ball lightning","Monsoon","Drought","Flash flood","Cold front","Warm front","Anticyclone","Atmospheric depression","Isobar","Relative humidity","Dew point","Northern lights","Sun halo","Sun dog","Heat mirage","Sandstorm","Dust storm","Snow drift","Black ice patch","Freezing rain","Lenticular cloud","Cumulonimbus cloud","Cirrus cloud","Stratus cloud","Cumulus cloud","Waterspout","Microburst","Weather bomb","Jet stream","El Nino","La Nina" },
            h = { "Derecho","Supercell storm","Mesocyclone","Downburst","Haboob","Firenado","Mammatus cloud","Shelf cloud","Nacreous cloud","Noctilucent cloud","Thermal inversion","Foehn effect","Katabatic wind","Anabatic wind","Polar jet stream","Southern oscillation","North Atlantic oscillation","Polar vortex","Cold air advection","Warm air advection","Weather radiosonde","Cup anemometer","Tipping bucket rain gauge","Nephoscope","Heliograph","Mercury barometer","Hair hygrometer","Geostationary weather satellite","Weather Doppler radar","Numerical weather prediction model","Barometric gradient","Wind shear","Atmospheric convection","Atmospheric instability","Saturation point","Atmospheric enthalpy","Earth's albedo","Atmospheric greenhouse effect","Trade wind belt","Intertropical convergence zone" },
        }},
        { id = "tools", name = "Tools", words = {
            e = { "Hammer","Screwdriver","Wrench","Pliers","Saw","Drill","Nail","Screw","Tape measure","Spirit level","Axe","Shovel","Rake","Hoe","Bucket","Ladder","Wheelbarrow","Paintbrush","Paint roller","Tarp","Scissors","Utility knife","Stapler","Strong glue","Duct tape","Rope","Chain","Padlock","Toolbox","Work gloves","Hard hat","Safety goggles","Dust mask","Workbench","Anvil","Metal file","Socket wrench","Power screwdriver","Sander","Angle grinder" },
            m = { "Tongs","Crowbar","Hand drill","Cordless drill","Jigsaw","Circular saw","Hacksaw","Rivet gun","Air compressor","Pneumatic nail gun","Laser level","Metal detector (DIY)","Multimeter","Soldering iron","Heat gun","Glue gun","Trowel","Float (plastering)","Cement mixer","Jackhammer","Hand truck","Pulley hoist","Winch","Car jack","Blowtorch","Welding machine","Electric planer","Router (woodworking)","Wood shaper","Mortising machine","Carpenter's workbench","Clamp","Bench dog","Carpenter's square","Drilling jig","Drill bit","Auger bit","Circular saw blade","Grinder disc","Sandpaper" },
            h = { "Bench vise","Threading die","Tap (threading)","Micrometer","Caliper","Dial indicator","Grinding machine","Metal lathe","Milling machine","Pillar drill","Punch press","Metal shears","Sheet metal bender","Sheet metal guillotine","TIG welder","MIG welder","Oxy-acetylene welding torch","Plasma cutter","Industrial compressor","Sandblaster","Ultrasonic cleaner","Hydraulic press","Hydraulic jack","Torque wrench","Bearing puller","Arbor press","Sawmill bench","Edging saw","Industrial spindle shaper","Belt sander","Jointer","Thickness planer","Tenoning machine","Chain mortiser","Band saw","Industrial sewing machine","Stamping press","Forging die","Blacksmith's anvil","Power hammer" },
        }},
        { id = "birds", name = "Birds", words = {
            e = { "Sparrow","Pigeon","Crow","Eagle","Owl (barn)","Owl (tawny)","Parrot","Duck","Swan","Hen","Rooster","Turkey","Hummingbird","Chickadee","Robin","Blackbird","Magpie","Stork","Flamingo","Penguin","Emperor penguin","Ostrich","Peacock","Pheasant","Partridge","Quail","Finch","Goldfinch","Swallow","Kingfisher","Heron","Cormorant","Seagull","Herring gull","Pelican","Toucan","Macaw","Cockatoo","Parakeet","Canary" },
            m = { "Golden eagle","Peregrine falcon","Common buzzard","Black kite","Griffon vulture","Condor","Osprey","Barn owl","Eagle owl","Snowy owl","Common crane","Ibis","Spoonbill","Avocet","Wading bird","Woodcock","Snipe","Lapwing","Plover","Curlew","Albatross","Northern gannet","Petrel","Shearwater","Guillemot","Puffin","Tern","Great crested grebe","Coot","Moorhen","Golden oriole","Hoopoe","Green woodpecker","Great spotted woodpecker","Cuckoo","Nightjar","Swift","Wagtail","Stonechat","Warbler" },
            h = { "Kakapo","Kiwi bird","Cassowary","Emu","Rhea","Secretary bird","Marabou stork","Hornbill","Quetzal","Trogon","Cotinga","Manakin","Sword-billed hummingbird","Crested hummingbird","Roller (bird)","Bee-eater","Weaver bird","Widowbird","Ruff (bird)","Bar-tailed godwit","Arctic tern","Giant petrel","Wandering albatross","Northern fulmar","Frigatebird","Tropicbird","Red-billed tropicbird","Horned grebe","Arctic loon","Common merganser","Common eider","Common goldeneye","Red-crested pochard","Common pochard","Common shelduck","Egyptian goose","Barnacle goose","Greylag goose","Black swan","Whooper swan" },
        }},
    },
}
